version: 2
jobs:
  build:
    docker:
      - image: golang:1.12
    steps:
      - checkout
      - run: apt update && apt install -y --no-install-recommends dbus libsecret-tools
      - run: go version
      - run: go install rsc.io/2fa
      - run: go test -v ./...
